### ISSUE TITLE
Im close...

### ISSUE THREAD

**Issue by JulieAlbers** [JulieAlbers/sections#1]
I'm feeling lost and I don't have a lab between now and the class when this is due. It looks close in the browser, but markbot is giving me a bunch of errors that I don't quite understand. The one I do understand is that it wants the image to be display: block, but when I do that it just messes everything up.
@thomasjbradley

**Comment by thomasjbradley** [comment]
Yeah, we definitely need to put display block on the image. It'd probably be a good idea to put the image into a `<div>`, then the image can be `block` and the `<div>` can be `inline-block`.

---

One of the error messages is telling you to put the class of `.btn` onto the `<a>` tag.
